dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install black isort
  - python setup.py install
script:
  - find src -name '*.py' | xargs black --check
  - find src -name '*.py' | xargs isort --check-only
  - make docs
